//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project2_2210900044.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_don_hang
    {
        public int ctdh_id { get; set; }
        public Nullable<int> dh_id { get; set; }
        public Nullable<int> sk_id { get; set; }
        public int soluong { get; set; }
        public Nullable<decimal> thanh_tien { get; set; }
    
        public virtual don_hang don_hang { get; set; }
        public virtual skin skin { get; set; }
    }
}
