//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project2_2210900044.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prj2_ngohoangminhEntities : DbContext
    {
        public prj2_ngohoangminhEntities()
            : base("name=prj2_ngohoangminhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chi_tiet_don_hang> chi_tiet_don_hang { get; set; }
        public virtual DbSet<don_hang> don_hang { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<skin> skins { get; set; }
        public virtual DbSet<thanh_toan> thanh_toan { get; set; }
    }
}
