//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project2_2210900044.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thanh_toan
    {
        public int tt_id { get; set; }
        public Nullable<int> dh_id { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public decimal sotienthanhtoan { get; set; }
        public string trangthai { get; set; }
    
        public virtual don_hang don_hang { get; set; }
    }
}
